### ISSUE TITLE
Samples do not load

### ISSUE THREAD

**Issue by neteca** [pseudonymous/better-better-booru#66]
I've tried a multitude of different settings combinations, including overriding logged-in settings, but sample images just will not load properly. 

When BBB is set to load sample images first, the sample does display for a split second, but then is replaced by the text, "Sample". Clicking the text loads the original image successfully. When BBB is set to load original images first or if the "view original" link is clicked, clicking the "view sample" link gives the error "Loading failed!" Disabling BBB causes samples to show normally. 

![sample](https://cloud.githubusercontent.com/assets/20213800/16469159/824eb040-3e1d-11e6-839a-325e700d16b0.png)
![sample2](https://cloud.githubusercontent.com/assets/20213800/16469160/8250021a-3e1d-11e6-9801-568b21139bc0.png)

Any help with this? Samples are kind of nice to have. Thanks!

**Comment by Moebius-Strip** [comment]
The fact that the sample image is displaying "Sample" when it fails to load should mean you're not using the most recent version of the script and that could very well be the problem. The more recent versions are updated to use the tags instead of "Sample" since Danbooru changed to that behavior.

Update by using [Greasy Fork/Sleazy Fork](https://sleazyfork.org/en/scripts/3575-better-better-booru) or you can use the [current work in progress](https://github.com/pseudonymous/better-better-booru/raw/gm-functions/better-better-booru.user.js) that will be released as version 7.3 before too long.

**Comment by neteca** [comment]
That worked! I didn't realize I was using an old version. Thanks much!
