### ISSUE TITLE
Problems when trying to Preview image

### ISSUE THREAD

**Issue by Okimo** [pseudonymous/better-better-booru#70]
Hmm where to begin...
I'm using "Imagus" its addon for Chrome that enables Preview the image of final page.
![preview](https://cloud.githubusercontent.com/assets/12627805/20089474/705f32ac-a587-11e6-96da-4b75662a2083.png)
Everything works fine only problem is when I try to preview any image taged as "Loli"and "Shota" it gets to infinite loop of loading.
![preview2](https://cloud.githubusercontent.com/assets/12627805/20089475/705fa278-a587-11e6-836e-dbec6c887aa1.png) 
Any other enabled tags by your script seems to work fine now :)

**Comment by Moebius-Strip** [comment]
Imagus appears to make use of the links generated by BBB, but what it does with those links afterwards is completely independent of this script. Imagus simply doesn't know how to find the hidden content on Danbooru.

If you want, you can edit your Imagus "sieve" for donmai.us by going into the options editing it under the sieve tab. What you should change is the following:
* Change the second field that displays "//danbooru.$1/posts/$2.json" to "//danbooru.$1/posts/$2" (remove the ".json").
* Change the third field that starts with ":" to this bit of JavaScript:
```
:
var postDoc = document.createElement("html");
postDoc.innerHTML = $._;

var imgCont = postDoc.querySelector("#image-container");
var domain = "http://" + location.hostname;
var postTags = imgCont.getAttribute("data-tags") || "";
var postExt = imgCont.getAttribute("data-file-ext") || ""; 
var isUgoira = (postExt === "zip" && /(?:^|\s)ugoira(?:$|\s)/.test(postTags));
var isFlash = (postExt === "swf");
var fileUrl = (isUgoira ? imgCont.getAttribute("data-large-file-url") : imgCont.getAttribute("data-file-url")) || "";

return (fileUrl && postTags && !isFlash ? [domain + fileUrl, postTags] : null);
```
* Erase the fourth and fifth fields.

In the end, it should look like this:
![imagus](https://cloud.githubusercontent.com/assets/3656227/20227844/5876d0f4-a81c-11e6-9e3c-dfdd308d60a7.png)

I don't know anything about making sieves in Imagus since there doesn't seem to be much documentation, but this should hopefully work without any issues.

**Comment by Okimo** [comment]
It works \o/
it has small delay of loading at start but then it works perfectly ^^
THANK YOU :3
![give-that-man-a-cookie](https://cloud.githubusercontent.com/assets/12627805/20270538/bbe1c58c-aa87-11e6-8f3b-de33e0f947ce.jpg)

**Comment by Moebius-Strip** [comment]
There will be a longer delay since the sieve is requesting an actual page now instead of just the basic information, but retrieving the post page is the only way to get file URL information for hidden/censored posts.

You may want to save this edit information somewhere since I've noticed that my changes to the donmai sieve have been reverted without me doing anything...
