### ISSUE TITLE
BBB causes the image to load twice

### ISSUE THREAD

**Issue by fireattack** [pseudonymous/better-better-booru#72]
This is a problem I encountered only recently.

All default settings, tested in clean profile of Firefox and Chrome.

To repro: 

1. open any post link, like http://danbooru.donmai.us/posts/2648611
1. You can clearly notice the image is loaded twice by flashing. 

It can be seen in the network tool as well:

![image](https://cloud.githubusercontent.com/assets/4130991/24315828/8ad30b54-10b7-11e7-9c3e-ad33a8751598.png)

Notice that they have slightly different URLs (albeit the same image).

Disabling BBB immediately fixed the problem.

**Comment by Moebius-Strip** [comment]
I suppose the real problem is the change in Danbooru's file names. The script has been rebuilding the post content for quite a long time in order to keep things simple. Backup your settings and try out the [current work in progress](https://github.com/pseudonymous/better-better-booru/raw/gm-functions/better-better-booru.user.js) from the other branch. If you're curious, a complete [list of changes](https://github.com/pseudonymous/better-better-booru/compare/gm-functions?expand=1) is available.

A summary of the current changes:
 * Added a "video volume" option for adjusting the starting volume of video posts.
 * Added a "disable tagged filenames" option to allow filename control for logged out users and manual (as needed) correction for logged in users.
 * Added a "video playback" blacklist option to allow control over the play/pause state of video posts.
 * Added a "hide hidden posts notice" option for hiding the Danbooru notice about hidden posts and gold accounts.
 * Added an "erase settings" section to the preferences tab for easily deleting BBB information.
 * Removed the "move save search" option since the save search button has been replaced by a link in the "+" search button.
 * Updated the "auto-hide sidebar" and "fixed sidebar" options to make them compatible with the "+" search button.
 * Updated to add back support for Danbooru's post to post hotkey navigation for searches while logged out.
 * Updated the methods for saving information so that settings can persist across all Danbooru domains and during private browsing.
 * Fixed various random search issues related to hidden posts.

**Comment by fireattack** [comment]
Thanks, it did fix the bug!

**Comment by Moebius-Strip** [comment]
Version 7.3 will be out on Fork before too long so you can do an official upgrade then.
