### ISSUE TITLE
Pool pages broken if prefs have many posts per page

### ISSUE THREAD

**Issue by Balorn** [pseudonymous/better-better-booru#76]
When viewing pools, if logged in and "posts per page" is set high, pools do not work; each page only shows the default number (20 I believe), the second page starts at 21 instead of whatever it should be for the number of posts set, and so on, but the number of pages is divided properly, meaning we can only see, for example, about the first 1/5 of the pool if we have posts per page set to 100.

**Comment by Balorn** [comment]
Changing 
`var thumbnail_count_default = 20;`
to 
`var thumbnail_count_default = 100;`
fixes it assuming I'm logged in and have 100 as my default, but it would be nice to be automatic; it seems to work fine for normal post searches, but not pools.

**Comment by Moebius-Strip** [comment]
I wasn't aware pools and favorite groups could have their thumbnails per a page changed by the account option but not by the URL limit value. Never really put much thought into it since this script started out as something only basic accounts would use. <_<;

I can add a separate preference option for telling the script how many thumbnails it should expect Danbooru to return by default. I'll look into making it automatically update, but the "posts per page" account setting is information that is only found in the account information unlike some other helpful info that is already in the page meta tags. Checking it would most likely have to be at intermittent times and during the submission of account setting changes.

**Comment by Moebius-Strip** [comment]
It isn't official yet, but you can use the this <a href="https://github.com/pseudonymous/better-better-booru/raw/Cache-%26-Count-Fixes/better-better-booru.user.js">work in progress</a> for now. The "thumbnail count default" setting is under the preference tabs with the other account related options.

**Comment by Moebius-Strip** [comment]
I've added an account check that is performed upon logging in to or changing account settings for Danbooru and the thumbnail count default option should be official in version 7.4 Greasy Fork before too long.
