### ISSUE TITLE
Old post image doesn't load when using BBB

### ISSUE THREAD

**Issue by fireattack** [pseudonymous/better-better-booru#78]
One example: http://danbooru.donmai.us/posts/1762

Pretty sure it's because their URL structure (with `/cached/`) is slightly different from the new one, and BBB replaced them to a wrong one (not sure why it replaces the file even when "Disable Tagged Filenames" is disabled).

**Comment by Moebius-Strip** [comment]
The posts have had their content rebuilt for a long time since it's the most straightforward and least "hacky" method of getting rid of event listeners attached the replaced HTML elements. The only real problem is the new cached path that Danbooru started using at some point. I've made some updates that should fix the problems with viewing posts and hopefully let the direct downloads option work decently. You can try the current <a href="https://github.com/pseudonymous/better-better-booru/raw/Cache-%26-Count-Fixes/better-better-booru.user.js">work in progress</a> and let met know how it goes.

**Comment by Tsubasaza** [comment]
Thanks for the quick fix, I think it works now because I've bookmarked the dead images and it's loading fine now.

**Comment by Tsubasaza** [comment]
Any news on the second patch? :V

**Comment by Tsubasaza** [comment]
Any news?

**Comment by Moebius-Strip** [comment]
> some images won't load, I think it's because I'm opening too many pages but I never had this problem before.. however, the dead images load if I refresh again

This is probably due to limitations on the Amazon bucket service that you're actually downloading the images through when dealing with cached images. I noticed the same problem when testing cached thumbnails. I've pushed version 7.4 so Greasy Fork should be officially updated to deal with the issue before too long.
