### ISSUE TITLE
Censored posts fixed on danbooru

### ISSUE THREAD

**Issue by nonamethanks** [pseudonymous/better-better-booru#82]
Heads up, https://github.com/r888888888/danbooru/pull/3239

It's not yet live in the site but it soon will be.

**Comment by nonamethanks** [comment]
And now's broken for good.

**Comment by impman** [comment]
Seconding for broken.

**Comment by Tsubasaza** [comment]
Broken

**Comment by FinderX** [comment]
Broken here too.

**Comment by Kazamimi** [comment]
Welp, rip.

**Comment by Moebius-Strip** [comment]
There goes the neighborhood. 😛 

Options removed.

**Comment by theredmanor** [comment]
So it's gone for good now?

**Comment by zqjpymbk** [comment]
evazion can eat a dick

**Comment by Type-kun** [comment]
It can be brought back if there's a builder+ kind enough to build and maintain a separate database storing `post_id, md5` pairs. There are already certain free online services that allow to store and query K/V pairs as a service ( https://keyvalue.xyz/ for example ), but such a thing can be easily built manually, provided someone is willing to share the bandwidth.

**Comment by Moebius-Strip** [comment]
@theredmanor More or less, yes. The information leaks have been plugged (finally <_<). Type-kun's suggestion would be the only viable option now.

**Comment by Tsubasaza** [comment]
Does it have to be a builder+? What about a regular gold account

**Comment by Moebius-Strip** [comment]
Actually, it does look like banned posts can be viewed by gold accounts. I thought those would have been limited to users a little further up the chain (builder+)...

**Comment by Tsubasaza** [comment]
What are the chances a gold account will get banned for doing this? :V

**Comment by Darayavaush** [comment]
There's no identifying information, so zero chance - the only activity would be occasional (like several times per day) pinging of the banned tags' pages.
It would be nice if in addition to information about md5 this DB stored child posts as well.

**Comment by Moebius-Strip** [comment]
Still work to do, but you can test the current work in progress here:
https://github.com/pseudonymous/better-better-booru/raw/hidden-update-test-branch/better-better-booru.user.js

Changes so far can be viewed here:
https://github.com/pseudonymous/better-better-booru/compare/hidden-update-test-branch?expand=1

**Comment by Darayavaush** [comment]
Great news, everyone: I managed to get id-md5 pairs for 7k banned posts since 2015.08: almost all loli posted since then (barring the times when a post was tagged with it >~1 week after posting) and almost all shota since an unknown point after that, with similar restriction. Grab away: https://gist.github.com/Darayavaush/6ab5aeee5b1eb5597df4bbb9f6b88b5e

**Comment by Moebius-Strip** [comment]
Things to be aware of:
* The file extension is currently not hidden in the data attributes for posts, while it is for the API. That could easily change though. Even if it doesn't, having the original file extension is very important with regards to speed and  limiting connections.
* Even if a database of IDs and filenames (MD5 hashes with extensions) is made, I'd think removing the ID number from hidden posts in the API would be a simple way to render such information much less useful. I'm not aware of any real reason why this couldn't be done.

**Comment by Darayavaush** [comment]
ID removal won't matter if we have a gold member supplying us with fresh data. In the worst case we can always make a DB with three columns - post ID, MD5, tags - and whenever a search is performed make a local lookup for banned images matching the tags and falling between the IDs of the first and last images, insert them into the page and resort the thumbnails.

**Comment by Type-kun** [comment]
http://puu.sh/x5Wu8/b8c7030be4.zip - here's the full id-md5-ext database, actual as of yesterday/today. Those are subject to change, you'll want to keep track of https://danbooru.donmai.us/post_replacements if you're gonna use it, but it's a good base to start with.

**Comment by Yoposoc** [comment]
You people are amazing.

**Comment by Tsubasaza** [comment]
Did it get solved or is it time to pay for Gold?

**Comment by Darayavaush** [comment]
Paying for Gold will only encourage them to censor more stuff and add more restrictions, so I don't recommend it. I can take care of the database and regular updates to it (and I already have a rudimentary version in the form of an RSS feed), but it needs to be integrated with BBB.

**Comment by Tsubasaza** [comment]
That's why I never bothered to support them,  If you can manage it and your Gold account gets suspended, I wouldn't mind gifting one.

**Comment by Darayavaush** [comment]
Nah, as I said above, there's zero chance of it being a problem - the only activity is three completely legit requests to the API every 12 hours. Worrying about this is simply not a productive usage of time.

**Comment by Tsubasaza** [comment]
Summoning Moebius-Strip, we've got volunteers  \o/

**Comment by pseudonymous** [comment]
replied in #86, closing.

I did think about the issue of this encouraging more restrictions, but I don't think working around it with scripts is a good way to protest that should it happen.

**Comment by Darayavaush** [comment]
This is disappointing. Well, I, for one, am not going to lay down and die. I've been thinking about how to make what I want to do work and I have an idea that seems workable, but my Javascript experience is fairly lacking. If someone at least moderately experienced in it wants to participate in this project, do drop me a line at archsinus@gmail.com . If not, I'll probably slap something together sooner or later myself.

**Comment by friendlyanon** [comment]
@Darayavaush I have sent you an email, check you Spam box in case it landed there

**Comment by bluefiberbread** [comment]
@pseudonymous restrictions against what? The script is basically not breaking into hidden features anymore.

@Darayavaush @friendlyanon will there be a fork so we can see the progress?

**Comment by Darayavaush** [comment]
@bluefiberbread An addon, not a fork. If nothing goes wrong, expect it this weekend.

**Comment by bluefiberbread** [comment]
@Darayavaush looking forward to it 👍

**Comment by Darayavaush** [comment]
All right, let's try disu shitto out. [Bonk](https://github.com/Darayavaush/decensooru).

**Comment by Moebius-Strip** [comment]
Welp, [pseudonymous already posted about the issue](https://github.com/pseudonymous/better-better-booru/issues/86#issuecomment-338350890) so it's now my turn. Why so late to the party? I'd say the reasons amount to about 1/3 laziness (I have my reputation as a self-proclaimed lazy bastard to upkeep, thank you very much), 1/3 paranoia (I didn't break something, did I? Is that a typo?),  and 1/3 packing/unpacking and moving furniture (literally resting my back as I type this).

I've chosen not to push the issue of hidden posts because, quite frankly, ever since [I banned myself from Danbooru](http://danbooru.donmai.us/bans?commit=Search&search%5Bbanner_name%5D=moebius_strip&search%5Border%5D=id_desc&search%5Buser_name%5D=moebius_strip&utf8=%E2%9C%93), browsing through image sites (be it Danbooru, 4chan, pixiv, whatever) hasn't really been a thing for me, so the hidden posts don't particularly bother me. Toying with the scripting is what interests me.

Regarding workarounds that would keeps things simple, I'd make a script that should load before BBB and make use of the node mutation observer. Using the BBB placeholder options that another user requested, hidden thumbnails could be replaced as they were inserted. When trying to actually view a post, the script would just have to immediately update missing data attributes and, in some cases like ugoira, perform a few other tasks. Nice, simple, and not too prone to breaking or falling behind when BBB is updated. Just my thoughts~...
