### ISSUE TITLE
Endless pages broken for restricted tags

### ISSUE THREAD

**Issue by OstrichRider** [pseudonymous/better-better-booru#85]
Shows one page of thumbnails then just lines for every other page. 

Solved by dropping back to 7.4

**Comment by Moebius-Strip** [comment]
Since you still see the posts, I assume you have a gold or above account. If so, that's the most likely root of the problem since this script started out as something only basic accounts and anonymous users would use. The next version should have much better compatibility with gold+ accounts. You can try the next version in progress [here](https://github.com/pseudonymous/better-better-booru/raw/hidden-update-cleanup/better-better-booru.user.js) and view the current list of changes [here](https://github.com/pseudonymous/better-better-booru/compare/hidden-update-cleanup?expand=1). Might backup your settings before doing so though.

**Comment by Moebius-Strip** [comment]
The newest version should hopefully resolve these problems.
